services:
  combiner:
    image: ghcr.io/wjbeckett/combiner:latest
    container_name: combiner
    restart: unless-stopped
    ports:
      - "5465:5465"
    volumes:
      - /mnt/user/data:/data
      - /mnt/user/appdata/combiner:/config
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5465/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
